### 1. 새 예약 생성 (POST)
# 이 요청을 먼저 실행하세요!
POST http://localhost:8080/api/appointments
Content-Type: application/json

{
  "customerName": "23",
  "chargerType": "CHaDEMO",
  "appointmentDate": "11/11/2025"
}

### 2. 모든 예약 조회 (GET)
# POST 실행 후, 이 요청을 실행해서 데이터가 잘 들어갔는지 확인합니다.
GET http://localhost:8080/api/appointments

### 3. 특정 예약 조회 (GET)
GET http://localhost:8080/api/appointments?chargerType=CHaDEMO&sortOrder=desc

### 4. 특정 예약 삭제 (DELETE)
# 2번 조회 결과에서 'id' 값을 확인하고,
# 아래 {id} 부분에 그 숫자를 넣으세요 (예: /api/appointments/1)
DELETE http://localhost:8080/api/appointments/1


### 5. 삭제 확인 (GET)
# DELETE 실행 후, 다시 이 요청을 실행해서 데이터가 비어있는지 확인합니다.
GET http://localhost:8080/api/appointments

### 6. 특정 예약 id로 조회 (GET)
GET http://localhost:8080/api/appointments/2